// This file is automatically generated. Do not edit it directly.
import { createClient, type StorageAdapter } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmhktnxqponixycsjcwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaGt0bnhxcG9uaXh5Y3NqY3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzYxMzcsImV4cCI6MjA3MDUxMjEzN30.KIsEJNV-xZaoZhgrm2ttjkyvNX-TwLriF25MmZ6iqRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const memoryStorage = new Map<string, string>();

const storageAdapter: StorageAdapter = {
  getItem: async (key) => memoryStorage.get(key) ?? null,
  setItem: async (key, value) => {
    memoryStorage.set(key, value);
  },
  removeItem: async (key) => {
    memoryStorage.delete(key);
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: 'sb-session',
    storageAdapter,
    persistSession: true,
    autoRefreshToken: true,
  },
});
